# Generated by Django 4.0.4 on 2022-06-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0005_mascota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
